### ISSUE TITLE
Error in Output

### ISSUE THREAD

**Issue by nathanagood** [awslabs/aws-cfn-lint-visual-studio-code#4]
I have two VS Code windows open. One of them seems to be working fine, but the second window has some errors in the console. I'm opening them up as two different issues just in case they aren't related--I hate conflating issues. 

Output is:
```
Settings have been updated...
Settings: [object Object]
Path set to: cfn-lint
Is CFN: false
running............. cfn-lint --format json --template /Users/nathgood/Code/generic-demos/simple-cloudformation-pipeline/cfn-pipeline.yml
Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cfnlint/__main__.py", line 51, in main
    defaults = template.get('Metadata', {}).get('cfn-lint', {}).get('config', {})
AttributeError: 'NoneType' object has no attribute 'get'

child process exited with code 1 and signal null
undefined:1
```

I can't paste the content of the template here as it contains non-public content, but it does not have a Metadata section.

**Comment by nathanagood** [comment]
Self-closing. I had an older version of `cfn-lint` installed and resolved the issue by shutting down VS Code, running the following commands, and starting VS Code back up:

```
$ cfn-lint --version # Noted it was an old version
$ pip uninstall cfn-lint
$ pip install cfn-lint
$ cfn-lint --version # Noted it was the new version
```

Doing a `pip install --upgrade` may have worked but I didn't try it first.
