### ISSUE TITLE
JSON parsing error in Output window

### ISSUE THREAD

**Issue by nathanagood** [awslabs/aws-cfn-lint-visual-studio-code#5]
Following error in output window:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/nathgood/.vscode/extensions/kddejong.vscode-cfn-lint-0.0.4/server/out/server.js:122:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Error - 10:14:54] Connection to server got closed. Server will not be restarted.
```

**Comment by nathanagood** [comment]
Closing. See resolution for #4 , which resolved this as well.
